site_name: "tech-docs-test"
site_description: "Documentation test"

nav:
  - Introduction: index.md
  - Contributing: contributing.md
  - Authentication: authentication.md
  - Errors: errors.md
  - Filter: filter.md
  - Pagination: pagination.md
  - Glossary: glossary.md
plugins:
  - techdocs-core
